### ISSUE TITLE
Create Node.js server

### ISSUE THREAD

**Issue by mbrandau** [mbrandau/simple-chat#1]
Create basic Node.js server exposing the /frontend/dist folder on http://localhost/ and creating the socket.io object.

**Comment by Pratyum** [comment]
Hey! I'd like to help implement this feature!

**Comment by pankajc007** [comment]
Start by creating a new file named “web_server.js”. Insert the following code into the file and save it.

var http = require("http");
var server = http.createServer(function(request, response) {
  response.writeHead(200, {"Content-Type": "text/html"});
  response.write("<!DOCTYPE "html">");
  response.write("<html>");
  response.write("<head>");
  response.write("<title>Hello World Page</title>");
  response.write("</head>");
  response.write("<body>");
  response.write("Hello World!");
  response.write("</body>");
  response.write("</html>");
  response.end();
});

server.listen(80);
console.log("Server is listening");

To start the server, type the command shown below. If everything works properly, you will see a message that the server is listening. Note that the example server attempts to bind to port 80, the standard HTTP port. If this port is already in use, or is restricted on your machine, you will experience an error.

node web_server.js

The next step is to connect to the server using a web browser. Launch your browser of choice, and direct it to either of the following links. In networking terms, localhost (and it’s IP address of 127.0.0.1) refers to the machine you are currently using. Your browser should be saying “Hello World!”.

http://localhost
http://127.0.0.1

**Comment by mbrandau** [comment]
@pankajc007 Your solution is not quite what I was looking for. You're not exposing the files in the `/frontend/dist/` folder and **socket.io** isn't used either.

**Comment by mbrandau** [comment]
Closed in #3
