### ISSUE TITLE
Add a license section to README.md

### ISSUE THREAD

**Issue by mbrandau** [mbrandau/simple-chat#20]

**Comment by gaurang444** [comment]
I would like to work on this.Can you please tell me the type of license MIT,BSD,GPL etc.

**Comment by mbrandau** [comment]
It's the MIT license. You can just link the LICENSE file

**Comment by ashenv93** [comment]
You already have the LICENSE file with the MIT License don't you?

**Comment by mbrandau** [comment]
That is correct. I still want to have a little notice in README though :smile:

**Comment by ashenv93** [comment]
Could you please check the pull request :)
PS : Sorry i deleted my comment by mistake.
