### ISSUE TITLE
Log all user related events (join,msg,leave) in web_server.js

### ISSUE THREAD

**Issue by mbrandau** [mbrandau/simple-chat#33]
Use `log.debug()`

**Comment by pszczolas** [comment]
Hello, I would like to work on this issue, but I'm not sure if i manage to do it. (I'm new in an angular and web-dev). Should I use sth like this to solve this problem?
```
io.on('join', joinInfo => {
/*logging*/
});
```

**Comment by mbrandau** [comment]
No problem @pszczolas, you don't need any knowledge of Angular for this one. The events are already there (`io.on('connection', ...)`, `socket.on('name', ...)`, etc.). It's just the logging messages you need to add.

**Comment by techpool** [comment]
Hey, I would like to take up this issue, can you just confirm whether log.debug can take multiple arguments or not?

**Comment by mbrandau** [comment]
@techpool log.*() methods work like util.format() so you can put as many args in as you want. @pszczolas is already working on it in #36.
