### ISSUE TITLE
Create a StartComponent for the frontend using Angular CLI

### ISSUE THREAD

**Issue by mbrandau** [mbrandau/simple-chat#5]
Run `ng g c Start` in the `frontend` folder.

**Comment by PriyankaGitHub7** [comment]
@mbrandau I would want to work on this. What should the start component have?

**Comment by mbrandau** [comment]
It should contain a title (just "simple-chat") and a simple form to enter a username.

**Comment by PriyankaGitHub7** [comment]
@mbrandau I have added the pull request https://github.com/mbrandau/simple-chat/pull/8

**Comment by mbrandau** [comment]
Closed as in #8
